name: tests

on:
  push:
    branches:
      - main  # Remplace par la branche que tu utilises si nécessaire
  pull_request:
    branches:
      - main

jobs:
  # Job pour les tests du backend
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code du backend
      - name: Checkout backend repository
        uses: actions/checkout@v2
        with:
          repository: misterwhite44/back_ubeers  # Répertoire du backend
          path: back_ubeers  # Le répertoire du backend cloné

      # Étape 2 : Installer les dépendances du backend
      - name: Install backend dependencies
        run: |
          cd back_ubeers  # Accède au répertoire du backend cloné
          pip install -r requirements.txt  # Installe les dépendances du backend si nécessaire

      # Étape 3 : Démarrer le serveur Flask en arrière-plan
      - name: Start Flask backend server
        run: |
          cd back_ubeers  # Répertoire du backend
          nohup python3 app.py &  # Démarre Flask en arrière-plan avec python3
          sleep 10  # Attends que le serveur démarre

      # Étape 4 : Exécuter les tests unitaires du backend
      - name: Run Backend Unit Tests
        run: |
          cd back_ubeers  # Accède au répertoire du backend
          python3 test_app.py  # Découvre et exécute tous les fichiers de test débutant par 'test_'

      # Étape 5 : Exécuter les tests d'intégration du backend
      - name: Run Backend Integration Tests
        run: |
          cd back_ubeers  # Accède au répertoire du backend
          python3 test_integration.py  # Exécute les tests d'intégration du backend

  # Job pour les tests du frontend avec Playwright
  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests  # S'assurer que le job backend est terminé avant de démarrer les tests frontend

    steps:
      # Étape 1 : Checkout du code du frontend
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          repository: misterwhite44/ubeer  # Répertoire du frontend
          path: ubeer  # Le répertoire du frontend cloné

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Remplace par la version souhaitée

      # Étape 3 : Installer les dépendances du frontend
      - name: Install frontend dependencies
        run: |
          cd ubeer  # Accède au répertoire du frontend cloné
          npm install  # Installe les dépendances du frontend

      # Étape 4 : Démarrer l'application frontend en arrière-plan
      - name: Start the frontend application
        run: |
          cd front_ubeers  # Répertoire du frontend
          nohup npm start &  # Démarre l'application frontend en arrière-plan
          sleep 10  # Attends que le serveur frontend démarre

      # Étape 5 : Exécuter les tests Playwright
      - name: Run Playwright Tests
        run: |
          cd front_ubeers  # Accède au répertoire du frontend
          npx playwright install  # Installer Playwright (si nécessaire)
          npx playwright test  # Exécuter les tests Playwright
