name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v2
        with:
          repository: misterwhite44/back_ubeers
          path: back_ubeers

      - name: Install backend dependencies
        run: |
          cd back_ubeers
          pip install -r requirements.txt
          pip install pytest

      - name: Run Backend Unit Tests
        run: |
          cd back_ubeers
          python3 test_app.py
        env:
          API_URL: https://back-ubeers.onrender.com
          REDIS_DISABLED: "true"

      - name: Run Backend Integration Tests
        run: |
          cd back_ubeers
          pytest -s test_integration.py
        env:
          API_URL: https://back-ubeers.onrender.com
          REDIS_DISABLED: "true"

  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          repository: misterwhite44/ubeer
          path: ubeer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd ubeer
          npm install

      - name: Build Frontend Application
        run: |
          cd ubeer
          npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Start the frontend application
        run: |
          cd ubeer
          nohup npm start &  
          sleep 10

      - name: Install and launch JMeter tests
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter
          export PATH=$PATH:/opt/jmeter/bin
          cd ubeer
          jmeter -n -t tests/jmeter/test_beers_load.jmx -l results.jtl

      - name: Run Playwright Tests
        run: |
          cd ubeer
          npx playwright install
          npx playwright test

# Optional: Reactivate OWASP ZAP later if needed.
#      - name: Run OWASP ZAP Security Scan
#        run: |
#          docker run --rm \
#            --volume ${{ github.workspace }}:/zap/wrk/:rw \
#            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
#              -t https://back-ubeers.onrender.com/breweries/ \
#              -r zap-breweries-report.html
